name: Trigger auto deployment for ml-fastapi-app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: hfacrmlops.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push container image to ACR
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            hfacrmlops.azurecr.io/huggingface-azure:latest
            hfacrmlops.azurecr.io/huggingface-azure:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container App
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt

            # Set registry credentials
            az containerapp registry set \
              --name ml-fastapi-app \
              --resource-group MLOps \
              --server hfacrmlops.azurecr.io \
              --username ${{ secrets.ACR_USERNAME }} \
              --password ${{ secrets.ACR_PASSWORD }}

            # Deploy new image
            az containerapp update \
              --name ml-fastapi-app \
              --resource-group MLOps \
              --image hfacrmlops.azurecr.io/huggingface-azure:latest
 